#pragma once

#include <cstddef>
#include <cstdint>

// =============================================================================
// config.h — Compile-time configuration constants
// =============================================================================

// Slow mode is compile-time gated
// Enable with -DROCEV2_SLOW_MODE=ON during CMake configure.
#ifndef ROCEV2_SLOW_MODE
#define ROCEV2_SLOW_MODE 0
#endif

#if ROCEV2_SLOW_MODE
static constexpr int SIM_TICK_MS = 40;
#else
static constexpr int SIM_TICK_MS = 10;
#endif

static constexpr char DEVICE_PATH[] = "/dev/mock_nic";
static constexpr size_t MAP_SIZE = 4096;
static constexpr int HTTP_PORT = 8080;

// Drain rate models the switch's output port capacity.
// The buffer fills only when sender_rate > DRAIN_RATE_PPS.
static constexpr uint32_t DEFAULT_RATE_PPS = 3000;
static constexpr uint32_t MAX_RATE_PPS = 6000;
static constexpr uint32_t DRAIN_RATE_PPS = 5000;



// Telemetry window — sized against the control loop, not the BDP packet count.
// DCQCN recovery time is approx. 1.5×RTT ≈ 15us: the CNP is generated by the RECEIVER,
// and one-way propagation is RTT/2 in each direction, so the signal loop is ~1×RTT and
// the rate settles ~0.5×RTT later. A 100ms window is ~6,667x longer than one recovery,
// so a congestion rate sustained above 20% over 100ms cannot be explained by normal
// in-flight packets or by healthy DCQCN oscillation — it means the queue is not draining
// and DCQCN has failed. Raise an alert for intervention.
static constexpr int WINDOW_MS = 100;
static constexpr double ALERT_THRESHOLD_PCT = 20.0;
